# Generated by Django 4.2.16 on 2024-10-09 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_items", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
