# Generated by Django 4.2.16 on 2024-10-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_item_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
    ]
