# Generated by Django 4.1 on 2024-10-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_category_item_information_about_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
