# Generated by Django 4.1 on 2024-10-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city',
        ),
    ]
