# Generated by Django 5.1.2 on 2024-10-21 04:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_chat_message"),
        ("web", "0008_delete_city"),
    ]

    operations = []
